[theme]
primaryColor = "#ffffff"               # White
backgroundColor = "#111f2a"            # Big Stone
secondaryBackgroundColor = "#608099"   # Hoki
textColor = "#bbbdbd"                  # Silver
font = "Moneta-Bold"
