[theme]
primaryColor = "#ffffff"               # White
backgroundColor = "#111f2a"            # Big Stone (dark blue)
secondaryBackgroundColor = "#608099"   # Hoki (light blue)
textColor = "#bbbdbd"                  # Silver

[layout]
mode = "wide"

[sidebar]
visibility = "expanded"

[footer]
backgroundColor = "#608099"
textColor = "#bbbdbd"
