[theme]
primaryColor = "#ffffff"               # White
backgroundColor = "#608099"            # Big Stone (light blue)
secondaryBackgroundColor = "#111f2a"   # Hoki (dark blue)
textColor = "#bbbdbd"                  # Silver

[layout]
mode = "wide"

[sidebar]
visibility = "expanded"

[footer]
backgroundColor = "#608099"
textColor = "#bbbdbd"
